name: Sincronización diaria Firebase-SQL

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Crear archivo .env desde Secrets
        run: |
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASS=${{ secrets.DB_PASS }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar primer script (SQL <-> Firebase)
        run: node sql_fire_2wsync.js

      - name: Ejecutar segundo script (Actualizar WorkDonevN)
        run: node firebasert_sql.js
